In [145]:
import numpy as np
import pandas as pd

df=pd.read_csv("../data/raw/GlobalWeatherRepository.csv")

In [146]:
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [147]:
print("columns present in dataset\n")
print(df.columns)
print("\n")
print("columns datatype\n")
print(df.dtypes)

columns present in dataset

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')


columns datatype

country                          object
location_name                    object
latitude                        float64
longitude                       float64
timezone                         object
last_updated_epoch                int64
last_updated                     object
temperature_celsius             float64
temperature_fahrenheit          float64
condition_text                   object
wind_mph                        float64
wind_kph                        float64
wind_degree                       int64
wind_direction                   object
pressure_mb                     float64
pressure_in                     float64
precip_mm                       float64
precip_in                       float64
humidity                          int64
cloud                             int64
feels_like_celsius              float64
feels_like_fahrenheit           float64
visibility_km                   float64
visibility_miles                float64
uv_index                        float64
gust_mph                        float64
gust_kph                        float64
air_quality_Carbon_Monoxide     float64
air_quality_Ozone               float64
air_quality_Nitrogen_dioxide    float64
air_quality_Sulphur_dioxide     float64
air_quality_PM2.5               float64
air_quality_PM10                float64
air_quality_us-epa-index          int64
air_quality_gb-defra-index        int64
sunrise                          object
sunset                           object
moonrise                         object
moonset                          object
moon_phase                       object
moon_illumination                 int64
dtype: object

In [148]:
print("dropping unwanted columns..\n")
df.drop(columns=['sunrise','sunset','moonrise','moonset','moon_phase','moon_illumination'
                 ,'temperature_fahrenheit','feels_like_fahrenheit','condition_text',
                 'feels_like_celsius','timezone','last_updated_epoch','timezone','wind_mph','wind_direction','pressure_in',
                 'precip_in','visibility_miles','gust_mph','air_quality_gb-defra-index','country','location_name','latitude','longitude'],inplace=True)
print("new columns\n")
print(df.columns)
print("new column datatypes\n")
print(df.dtypes)

dropping unwanted columns..

new columns

Index(['last_updated', 'temperature_celsius', 'wind_kph', 'wind_degree',
       'pressure_mb', 'precip_mm', 'humidity', 'cloud', 'visibility_km',
       'uv_index', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index'],
      dtype='object')
new column datatypes

last_updated                     object
temperature_celsius             float64
wind_kph                        float64
wind_degree                       int64
pressure_mb                     float64
precip_mm                       float64
humidity                          int64
cloud                             int64
visibility_km                   float64
uv_index                        float64
gust_kph                        float64
air_quality_Carbon_Monoxide     float64
air_quality_Ozone               float64
air_quality_Nitrogen_dioxide    float64
air_quality_Sulphur_dioxide     float64
air_quality_PM2.5               float64
air_quality_PM10                float64
air_quality_us-epa-index          int64
dtype: object

DATASET DESCRIBE

In [149]:
print("Description od Dataset")
df.describe()

Description od Dataset

,temperature_celsius,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,visibility_km,uv_index,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index
count,91197.000000,91197.000000,91197.000000,91197.000000,91197.000000,91197.000000,91197.000000,91197.000000,91197.000000,91197.000000,91197.00000,91197.000000,91197.000000,91197.000000,91197.000000,91197.000000,91197.000000
mean,22.739381,13.327251,170.862046,1013.944439,0.140891,63.831255,39.420244,9.634309,3.947890,18.693339,516.70776,63.462878,15.561760,11.290716,26.207392,54.278045,1.760760
std,9.029556,12.952662,103.014196,11.651696,0.599237,24.235502,33.771522,2.521447,3.627169,14.948535,853.55118,32.760678,25.970284,41.759543,41.316814,164.980740,0.985832
min,-24.900000,3.600000,1.000000,947.000000,0.000000,2.000000,0.000000,0.000000,0.000000,3.600000,-9999.00000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000
25%,18.000000,6.500000,83.000000,1010.000000,0.000000,47.000000,0.000000,10.000000,0.600000,10.600000,236.80000,43.000000,1.295000,0.800000,7.215000,10.545000,1.000000
50%,25.000000,11.200000,165.000000,1013.000000,0.000000,69.000000,27.000000,10.000000,3.200000,16.100000,327.45000,61.000000,4.625000,2.405000,14.985000,22.015000,1.000000
75%,28.400000,18.400000,257.000000,1017.000000,0.030000,83.000000,75.000000,10.000000,7.000000,24.800000,505.78800,80.000000,17.390000,9.065000,30.155000,46.805000,2.000000
max,49.200000,2963.200000,360.000000,3006.000000,42.240000,100.000000,100.000000,32.000000,16.300000,2970.400000,38879.39800,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000

VARIABLES DESCRIPTION

In [150]:
print("unique values in each columns of dataset\n")
print(df.nunique())

unique values in each columns of dataset

last_updated                    15414
temperature_celsius               655
wind_kph                          179
wind_degree                       360
pressure_mb                        89
precip_mm                         586
humidity                           99
cloud                             101
visibility_km                      69
uv_index                          163
gust_kph                          752
air_quality_Carbon_Monoxide      3821
air_quality_Ozone                 635
air_quality_Nitrogen_dioxide     1721
air_quality_Sulphur_dioxide      1731
air_quality_PM2.5                3608
air_quality_PM10                 5319
air_quality_us-epa-index            6
dtype: int64

In [151]:
print("shape of dataset: ",df.shape)

shape of dataset:  (91197, 18)

DATA WARGLING

REMOVE EXACT DUPLICATES

In [152]:
print("checking for duplicated rows\n")
print("no.of exact duplicated rows : ",df.duplicated().sum())

df=df.drop_duplicates()
print("shape of dataset after removing duplicates:",df.shape)

checking for duplicated rows

no.of exact duplicated rows :  359
shape of dataset after removing duplicates: (90838, 18)

df

In [153]:
df.head()

,last_updated,temperature_celsius,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,visibility_km,uv_index,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index
0,2024-05-16 13:15,26.6,13.3,338,1012.0,0.0,24,30,10.0,7.0,15.3,277.0,103.0,1.1,0.2,8.4,26.6,1
1,2024-05-16 10:45,19.0,11.2,320,1012.0,0.1,94,75,10.0,5.0,18.4,193.6,97.3,0.9,0.1,1.1,2.0,1
2,2024-05-16 09:45,23.0,15.1,280,1011.0,0.0,29,0,10.0,5.0,22.3,540.7,12.2,65.1,13.4,10.4,18.4,1
3,2024-05-16 10:45,6.3,11.9,215,1007.0,0.3,61,100,2.0,2.0,13.7,170.2,64.4,1.6,0.2,0.7,0.9,1
4,2024-05-16 09:45,26.0,13.0,150,1011.0,0.0,89,50,10.0,8.0,20.2,2964.0,19.0,72.7,31.5,183.4,262.3,5

HANDLE MISSING VALUES

In [154]:
print("Handling missing values..\n")

numeric_cols=df.select_dtypes(include=np.number).columns
for col in numeric_cols:
    if df[col].isnull().sum() >0:
        median_value=df[col].median()
        df[col]=df[col].fillna(median_value)
        null_count=df[col].isnull().sum()
        print(f"Filled {null_count} missing values in {col} with {median_value}")

#for categorical columns
categorical_col=df.select_dtypes(include='object').columns
for col in categorical_col:
    if df[col].isnull().sum() >0:
        mode_val=df[col].mode()[0]
        null_count=df[col].isnull().sum()
        df[col]=df[col].fillna(mode_val)
        print(f"Filled {null_count} rows of {col} with {mode_val}")

Handling missing values..

DETECT & TREAT OUTLIERS

In [155]:
print("Detecting and treating outliers..\n")
orginal_count=len(df)
def winsorize_series(series,lower_quantile=0.01,upper_quantile=0.99):
    lower_bound=series.quantile(lower_quantile)
    upper_bound=series.quantile(upper_quantile)
    return series.clip(lower_bound,upper_bound)
# Define reasonable bounds for each column (more permissive than standard ranges)
column_bounds = {
        'latitude': (-90, 90),  # Valid latitude range
        'longitude': (-180, 180),  # Valid longitude range
        'temperature_celsius': (-50, 60),  # Extreme but possible temperatures
        'wind_kph': (0, 200),  # Very strong wind but possible in hurricanes
        'wind_degree': (0, 360),  # Valid wind direction degrees
        'pressure_mb': (800, 1100),  # Extreme but possible pressure values
        'precip_mm': (0, 500),  # Very heavy rainfall but possible
        'humidity': (0, 100),  # Valid humidity percentage
        'cloud': (0, 100),  # Valid cloud coverage percentage
        'visibility_km': (0, 50),  # Very poor to excellent visibility
        'uv_index': (0, 20),  # Extreme but possible UV index
        'gust_kph': (0, 250),  # Very strong wind gusts
        'air_quality_Carbon_Monoxide': (0, 10000),  # Wide range for air quality metrics
        'air_quality_Ozone': (0, 500),
        'air_quality_Nitrogen_dioxide': (0, 500),
        'air_quality_Sulphur_dioxide': (0, 500),
        'air_quality_PM2.5': (0, 500),
        'air_quality_PM10': (0, 1000),
        'air_quality_us-epa-index': (0, 6)  # EPA index typically 1-6
    }
print("First pass: Apply reasonable bounds to prevent impossible values\n")
for col, (lower, upper) in column_bounds.items():
        if col in df.columns:
            # Count extreme values before capping
            extreme_low = (df[col] < lower).sum()
            extreme_high = (df[col] > upper).sum()
            
            if extreme_low > 0 or extreme_high > 0:
                print(f"  {col}: Capping {extreme_low} below {lower}, {extreme_high} above {upper}")
                df[col] = df[col].clip(lower, upper)
print("Second pass: Winsorize extreme but possible values (1st and 99th percentiles)\n")
columns_to_winsorize = [
        'temperature_celsius', 'wind_kph', 'pressure_mb', 'precip_mm',
        'humidity', 'cloud', 'visibility_km', 'uv_index', 'gust_kph',
        'air_quality_Carbon_Monoxide', 'air_quality_Ozone',
        'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide',
        'air_quality_PM2.5', 'air_quality_PM10'
    ]
for col in columns_to_winsorize:
        if col in df.columns:
           
            q01 = df[col].quantile(0.01)
            q99 = df[col].quantile(0.99)
            extreme_low = (df[col] < q01).sum()
            extreme_high = (df[col] > q99).sum()
            
            if extreme_low > 0 or extreme_high > 0:
                print(f"  {col}: Winsorizing {extreme_low+extreme_high} extreme values "
                      f"(below {q01:.2f}, above {q99:.2f})")
                df[col] = winsorize_series(df[col])
# For air quality index, ensure it's integer and within valid range
if 'air_quality_us-epa-index' in df.columns:
        invalid_aqi = ((df['air_quality_us-epa-index'] < 1) | 
                       (df['air_quality_us-epa-index'] > 6) |
                       (df['air_quality_us-epa-index'].isnull())).sum()
        
        if invalid_aqi > 0:
            print(f"  AQI: Fixing {invalid_aqi} invalid values")
            # Convert to integer and cap at valid range
            df['air_quality_us-epa-index'] = (df['air_quality_us-epa-index']
                                             .fillna(1)
                                             .clip(1, 6)
                                             .round()
                                             .astype(int))
    
print(f"Rows preserved: {len(df)}/{orginal_count} ({len(df)/orginal_count*100:.2f}%)")

Detecting and treating outliers..

First pass: Apply reasonable bounds to prevent impossible values

  wind_kph: Capping 0 below 0, 4 above 200
  pressure_mb: Capping 0 below 800, 2 above 1100
  gust_kph: Capping 0 below 0, 3 above 250
  air_quality_Carbon_Monoxide: Capping 1 below 0, 114 above 10000
  air_quality_Sulphur_dioxide: Capping 1 below 0, 1 above 500
  air_quality_PM2.5: Capping 0 below 0, 86 above 500
  air_quality_PM10: Capping 1 below 0, 349 above 1000
Second pass: Winsorize extreme but possible values (1st and 99th percentiles)

  temperature_celsius: Winsorizing 1754 extreme values (below -1.70, above 41.00)
  wind_kph: Winsorizing 908 extreme values (below 3.60, above 37.40)
  pressure_mb: Winsorizing 1615 extreme values (below 996.00, above 1032.00)
  precip_mm: Winsorizing 908 extreme values (below 0.00, above 2.16)
  humidity: Winsorizing 749 extreme values (below 9.00, above 100.00)
  visibility_km: Winsorizing 915 extreme values (below 1.50, above 24.00)
  uv_index: Winsorizing 885 extreme values (below 0.00, above 13.50)
  gust_kph: Winsorizing 1778 extreme values (below 4.00, above 53.00)
  air_quality_Carbon_Monoxide: Winsorizing 1813 extreme values (below 141.90, above 3615.18)
  air_quality_Ozone: Winsorizing 1785 extreme values (below 0.80, above 163.00)
  air_quality_Nitrogen_dioxide: Winsorizing 909 extreme values (below 0.00, above 123.51)
  air_quality_Sulphur_dioxide: Winsorizing 909 extreme values (below 0.00, above 125.86)
  air_quality_PM2.5: Winsorizing 916 extreme values (below 0.50, above 177.97)
  air_quality_PM10: Winsorizing 1739 extreme values (below 0.90, above 572.02)
Rows preserved: 90838/90838 (100.00%)

OPTIMIZATION OF DATA TYPES

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 90838 entries, 0 to 91196
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   last_updated                  90838 non-null  object
 1   temperature_celsius           90838 non-null  float64
 2   wind_kph                      90838 non-null  float64
 3   wind_degree                   90838 non-null  int64
 4   pressure_mb                   90838 non-null  float64
 5   precip_mm                     90838 non-null  float64
 6   humidity                      90838 non-null  int64
 7   cloud                         90838 non-null  int64
 8   visibility_km                 90838 non-null  float64
 9   uv_index                      90838 non-null  float64
 10  gust_kph                      90838 non-null  float64
 11  air_quality_Carbon_Monoxide   90838 non-null  float64
 12  air_quality_Ozone             90838 non-null  float64
 13  air_quality_Nitrogen_dioxide  90838 non-null  float64
 14  air_quality_Sulphur_dioxide   90838 non-null  float64
 15  air_quality_PM2.5             90838 non-null  float64
 16  air_quality_PM10              90838 non-null  float64
 17  air_quality_us-epa-index      90838 non-null  int64
dtypes: float64(13), int64(4), object(1)
memory usage: 13.2+ MB

In [159]:
def optimize_data_types(df):
    print("=== DATA TYPE OPTIMIZATION ===")
    original_memory = df.memory_usage(deep=True).sum() / 1024**2
    print(f"Original memory: {original_memory:.2f} MB")
    
    df_opt = df.copy()
    
   
    # 2. CONVERT DATETIME
    df_opt['last_updated'] = pd.to_datetime(df_opt['last_updated'])
    
    # 3. DOWNCAST FLOAT64 â†’ FLOAT32 (50% SAVINGS)
    float_cols = [
        'temperature_celsius', 'wind_kph',
        'pressure_mb', 'precip_mm', 'visibility_km', 'uv_index', 'gust_kph',
        'air_quality_Carbon_Monoxide', 'air_quality_Ozone',
        'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide',
        'air_quality_PM2.5', 'air_quality_PM10'
    ]
    
    for col in float_cols:
        df_opt[col] = pd.to_numeric(df_opt[col], downcast='float')
    
    # 4. OPTIMIZE INTEGER COLUMNS (BIG SAVINGS)
    # humidity: 0-100 â†’ uint8 (1 byte instead of 8)
    df_opt['humidity'] = df_opt['humidity'].astype('uint8')
    
    # cloud: 0-100 â†’ uint8 (1 byte instead of 8)
    df_opt['cloud'] = df_opt['cloud'].astype('uint8')
    
    # wind_degree: 0-360 â†’ uint16 (2 bytes instead of 8)
    df_opt['wind_degree'] = df_opt['wind_degree'].astype('uint16')
    
    # air_quality_us-epa-index: 1-6 â†’ uint8 (1 byte instead of 8)
    df_opt['air_quality_us-epa-index'] = df_opt['air_quality_us-epa-index'].astype('uint8')
    
    # Calculate savings
    optimized_memory = df_opt.memory_usage(deep=True).sum() / 1024**2
    savings = original_memory - optimized_memory
    savings_pct = (savings / original_memory) * 100
    
    print(f"Optimized memory: {optimized_memory:.2f} MB")
    print(f"Memory saved: {savings:.2f} MB ({savings_pct:.1f}%)")
    
    return df_opt
df=optimize_data_types(df)

=== DATA TYPE OPTIMIZATION ===
Original memory: 18.80 MB
Optimized memory: 6.32 MB
Memory saved: 12.47 MB (66.4%)

In [160]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 90838 entries, 0 to 91196
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   last_updated                  90838 non-null  datetime64[ns]
 1   temperature_celsius           90838 non-null  float32
 2   wind_kph                      90838 non-null  float32
 3   wind_degree                   90838 non-null  uint16
 4   pressure_mb                   90838 non-null  float32
 5   precip_mm                     90838 non-null  float32
 6   humidity                      90838 non-null  uint8
 7   cloud                         90838 non-null  uint8
 8   visibility_km                 90838 non-null  float32
 9   uv_index                      90838 non-null  float32
 10  gust_kph                      90838 non-null  float32
 11  air_quality_Carbon_Monoxide   90838 non-null  float32
 12  air_quality_Ozone             90838 non-null  float32
 13  air_quality_Nitrogen_dioxide  90838 non-null  float32
 14  air_quality_Sulphur_dioxide   90838 non-null  float32
 15  air_quality_PM2.5             90838 non-null  float32
 16  air_quality_PM10              90838 non-null  float32
 17  air_quality_us-epa-index      90838 non-null  uint8
dtypes: datetime64[ns](1), float32(13), uint16(1), uint8(3)
memory usage: 6.3 MB

FEATURE ENGINEERING

In [161]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split
# For creating new features
from sklearn.preprocessing import PolynomialFeatures

FEATURE ENGINEERING ON last_updated column

In [162]:
df['hour']=df['last_updated'].dt.hour
df['day_of_week']=df['last_updated'].dt.dayofweek
df['month']=df['last_updated'].dt.month
df['is_weekend'] = (df['day_of_week'] >= 5).astype(int)

def get_part_of_day(hour):
    if 5 <= hour < 12:
        return 'morning'
    elif 12 <= hour < 17:
        return 'afternoon'
    elif 17 <= hour < 21:
        return 'evening'
    else:
        return 'night'

df['part_of_day'] = df['hour'].apply(get_part_of_day)
df.drop('last_updated',axis=1,inplace=True)

ENCODE CATEGORICAL FEATURES

In [163]:
df.nunique()

temperature_celsius              428
wind_kph                          95
wind_degree                      360
pressure_mb                       37
precip_mm                        217
humidity                          92
cloud                            101
visibility_km                     53
uv_index                         136
gust_kph                         491
air_quality_Carbon_Monoxide     3030
air_quality_Ozone                476
air_quality_Nitrogen_dioxide    1320
air_quality_Sulphur_dioxide     1236
air_quality_PM2.5               3118
air_quality_PM10                4786
air_quality_us-epa-index           6
hour                              24
day_of_week                        7
month                             12
is_weekend                         2
part_of_day                        4
dtype: int64

In [164]:
df.head()

,temperature_celsius,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,visibility_km,uv_index,gust_kph,...,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,hour,day_of_week,month,is_weekend,part_of_day
0,26.6,13.3,338,1012.0,0.0,24,30,10.0,7.0,15.300000,...,1.100000,0.2,8.400000,26.600000,1,13,3,5,0,afternoon
1,19.0,11.2,320,1012.0,0.1,94,75,10.0,5.0,18.400000,...,0.900000,0.1,1.100000,2.000000,1,10,3,5,0,morning
2,23.0,15.1,280,1011.0,0.0,29,0,10.0,5.0,22.299999,...,65.099998,13.4,10.400000,18.400000,1,9,3,5,0,morning
3,6.3,11.9,215,1007.0,0.3,61,100,2.0,2.0,13.700000,...,1.600000,0.2,0.700000,0.900000,1,10,3,5,0,morning
4,26.0,13.0,150,1011.0,0.0,89,50,10.0,8.0,20.200001,...,72.699997,31.5,177.970001,262.299988,5,9,3,5,0,morning

SAVING CLEANED DATASET

In [165]:
import os
os.makedirs("..data/cleaned",exist_ok=True)
df.to_csv("../data/cleaned/cleaned_dataset.csv",index=False)
print("âœ… Cleaned dataset saved at data/cleaned/cleaned_dataset.csv")

âœ… Cleaned dataset saved at data/cleaned/cleaned_dataset.csv